/**
 * The Haven six-month plan, as data.
 *
 * GENERATED by scripts/build-haven-plan.py from the client-facing milestone
 * tracker. Do not edit by hand: edit the tracker (or the EXTRA block in the
 * generator) and re-run, so the daily push cannot drift from the plan Haven
 * was sold.
 *
 * `addedByCfa` marks the OKR, JD and KPI items, which are our delivery
 * structure rather than lines in the tracker PDF the board already has.
 */

export type PlanTask = {
  what: string;
  done: string;
  owner: string;
  lever: string;
  addedByCfa: boolean;
  /** Workstream key in lib/haven-delivery.ts. 'cfa' is ours, not theirs. */
  seat: string;
};

export type PlanMonth = {
  title: string;
  theme: string;
  target: string;
  tasks: PlanTask[];
};

export const PLAN: PlanMonth[] = [
  {
    "title": "Month 1 - Days 1-30",
    "theme": "Stabilise and switch on the engine",
    "target": "~N16M / mo",
    "tasks": [
      {
        "what": "Billing & revenue-capture system live",
        "done": "Every service delivered is recorded and billed; the handover-sheet record retired.",
        "owner": "Finance + C4A",
        "lever": "Lever 6",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Tariff mystery-shop + reprice the zero-priced lines",
        "done": "5-6 peers benchmarked; the 80.9% of lines at zero given defensible prices.",
        "owner": "C4A",
        "lever": "Lever 6",
        "addedByCfa": false,
        "seat": "cfa"
      },
      {
        "what": "Receivables recovery push (Leadway & NEM)",
        "done": "First tranche of the N4.2M recovered; a weekly chase routine running.",
        "owner": "Finance",
        "lever": "Lever 7",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Vendor-managed inventory partner selected",
        "done": "Consignment terms agreed to free the N2.77M in stock and end stockouts.",
        "owner": "Pharmacy + C4A",
        "lever": "Lever 7",
        "addedByCfa": false,
        "seat": "pharmacy"
      },
      {
        "what": "Referral portal v1 live + inbound analyst calling",
        "done": "Portal takes referrals; the dedicated analyst working the hospital call list.",
        "owner": "Business dev",
        "lever": "Lever 1",
        "addedByCfa": false,
        "seat": "bd"
      },
      {
        "what": "NICU repriced + hyperlocal catchment mapped",
        "done": "New NICU rate set; every maternity unit and Ob/Gyn near GRA Ikeja ranked.",
        "owner": "Dr Odedina + BD",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "nicu"
      },
      {
        "what": "Senior operations leader: role defined, search live",
        "done": "Spec and KPIs written; candidates being sourced.",
        "owner": "Board + C4A",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "board"
      },
      {
        "what": "Safety & just-culture quick wins",
        "done": "Crash-cart standard locked; just-culture standard drafted from the survey.",
        "owner": "Clinical lead",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "A one-page job description for every named seat",
        "done": "Each seat on this plan has a written JD: what it owns, what it decides alone, what it escalates. Signed by the holder.",
        "owner": "HR + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "hr"
      },
      {
        "what": "Three to five KPIs per seat, with a baseline",
        "done": "Every JD carries its measures and today's number against each, so month 6 can be read against something.",
        "owner": "HR + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "hr"
      },
      {
        "what": "Quarter one OKRs agreed with the board",
        "done": "Three objectives for the quarter, each with measurable key results tied to the run-rate ladder, agreed not announced.",
        "owner": "Board + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "board"
      },
      {
        "what": "Re-onboarding designed, and the first cohort through it",
        "done": "A real induction, not an email: who Haven is now, what it is for, what is expected and what each person can expect back. First cohort attended and signed.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      },
      {
        "what": "The culture baseline published to staff",
        "done": "What the safety and culture survey actually said, given back to the people who answered it, including the uncomfortable parts.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      }
    ]
  },
  {
    "title": "Month 2 - Days 31-60",
    "theme": "Professionalise, drive the NICU, launch the club",
    "target": "~N24M / mo",
    "tasks": [
      {
        "what": "Senior operations leader in post",
        "done": "Hired and running the facility day to day.",
        "owner": "Board",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "board"
      },
      {
        "what": "NICU growth drive running",
        "done": "Ob/Gyn NICU tours underway; high-risk antenatal pathway live; first referral agreements signed.",
        "owner": "Dr Odedina + BD",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "nicu"
      },
      {
        "what": "Neonatal transport ambulance operational",
        "done": "A mobile NICU that collects sick babies from referring facilities.",
        "owner": "Operations",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "operations"
      },
      {
        "what": "Haven Club launched",
        "done": "Three plans live; Bump-to-Baby on-ramp open; first members enrolling at every discharge.",
        "owner": "Membership + C4A",
        "lever": "Lever 5",
        "addedByCfa": false,
        "seat": "membership"
      },
      {
        "what": "Management reporting dashboard live",
        "done": "One reconciled monthly report: revenue by line, EBITDA, occupancy, receivables.",
        "owner": "Finance + C4A",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Staff app configured + incentives redesigned",
        "done": "HR app running onboarding, rota, payslips, KPIs; new commission/JD/KPI structure drafted.",
        "owner": "HR + C4A",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "hr"
      },
      {
        "what": "Every seat has had its JD and KPI conversation",
        "done": "Each person has sat down with their JD and measures and said yes to them. Not a circulated document.",
        "owner": "HR + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "hr"
      },
      {
        "what": "Every member of staff re-onboarded",
        "done": "Everyone has been through it, including night shifts and the longest-serving. New starters now join through the same door.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      },
      {
        "what": "What gets recognised, named out loud",
        "done": "The behaviours Haven rewards and the ones it will not carry, written down and visible, and the first recognitions actually made.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      }
    ]
  },
  {
    "title": "Month 3 - Days 61-90",
    "theme": "Add the lines and turn on marketing",
    "target": "~N30M / mo",
    "tasks": [
      {
        "what": "Home care & telemedicine live",
        "done": "Newborn home checks, post-discharge visits, home phototherapy, virtual follow-ups.",
        "owner": "Clinical",
        "lever": "Lever 9",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "Nutrition, lactation & therapy clinics open",
        "done": "Nutrition/lactation and developmental & therapy (speech, OT, physio) services live.",
        "owner": "Clinical",
        "lever": "Lever 9",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "First sessional paediatric surgery lists",
        "done": "Visiting surgeon sessions running; theatre in use.",
        "owner": "Clinical",
        "lever": "Lever 3",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "Lab outsourcing live",
        "done": "Accredited reference partner running; point-of-care core kept in-house, rest sent out.",
        "owner": "Clinical + C4A",
        "lever": "Lever 7",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "Corporate & school retainers: first signed",
        "done": "First contracts closed, starting from the Toddler Town relationship.",
        "owner": "Business dev",
        "lever": "Lever 4",
        "addedByCfa": false,
        "seat": "bd"
      },
      {
        "what": "Marketing engine on",
        "done": "Events calendar live with the first community event; podcast launched; agency held to booked leads.",
        "owner": "Marketing / agency",
        "lever": "Lever 10",
        "addedByCfa": false,
        "seat": "marketing"
      },
      {
        "what": "Club membership building",
        "done": "First cohort of members enrolling steadily at discharge and registration.",
        "owner": "Membership lead",
        "lever": "Lever 5",
        "addedByCfa": false,
        "seat": "membership"
      },
      {
        "what": "First OKR review",
        "done": "Quarter one key results scored honestly, and quarter two set from what the scoring showed.",
        "owner": "Board + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "board"
      },
      {
        "what": "Just culture tested on a real incident",
        "done": "The first incident under the new standard handled visibly: what happened, what changed, and nobody punished for reporting it.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      }
    ]
  },
  {
    "title": "Month 4 - Days 91-120",
    "theme": "Scale demand and embed the culture",
    "target": "~N36M / mo",
    "tasks": [
      {
        "what": "NICU occupancy scaling into the season",
        "done": "Cots filling on the referral pipeline; occupancy climbing week on week.",
        "owner": "Dr Odedina + BD",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "nicu"
      },
      {
        "what": "Referral network widened",
        "done": "Beyond hyperlocal; the analyst pipeline at full tilt with tracked conversion.",
        "owner": "Business dev",
        "lever": "Lever 1",
        "addedByCfa": false,
        "seat": "bd"
      },
      {
        "what": "More HMO panels live + corporates growing",
        "done": "New empanelments active; corporate and school retainers expanding.",
        "owner": "Finance + BD",
        "lever": "Lever 4",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Club events cadence running; membership growing",
        "done": "Regular member events; membership base building toward target.",
        "owner": "Membership lead",
        "lever": "Lever 5",
        "addedByCfa": false,
        "seat": "membership"
      },
      {
        "what": "Cultural transformation embedded",
        "done": "Onboarding, SOPs, culture & EQ training, peer-to-peer learning, and the new incentives all live.",
        "owner": "HR + Clinical",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "hr"
      },
      {
        "what": "Add-on clinics maturing",
        "done": "Dentistry, audiology and allergy/asthma added as they come ready.",
        "owner": "Clinical",
        "lever": "Lever 9",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "Leaders doing it, not announcing it",
        "done": "Heads of department holding the standards in their own teams without being prompted, with examples anyone can point to.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      }
    ]
  },
  {
    "title": "Month 5 - Days 121-150",
    "theme": "Fill the beds at peak and optimise yield",
    "target": "~N42M / mo",
    "tasks": [
      {
        "what": "NICU near full through the high season",
        "done": "Peak occupancy sustained; transport and referrals feeding the cots.",
        "owner": "Dr Odedina + BD",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "nicu"
      },
      {
        "what": "Tariff second tranche / yield optimisation",
        "done": "Second price step where defensible; payer mix actively managed for margin.",
        "owner": "Finance + C4A",
        "lever": "Lever 6",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Surgery lists regular; theatre utilisation up",
        "done": "Sessional surgery a steady line; theatre time well used.",
        "owner": "Clinical",
        "lever": "Lever 3",
        "addedByCfa": false,
        "seat": "clinical"
      },
      {
        "what": "Membership ramp accelerating; renewals live",
        "done": "Enrolment accelerating; retention and renewal mechanics in place.",
        "owner": "Membership lead",
        "lever": "Lever 5",
        "addedByCfa": false,
        "seat": "membership"
      },
      {
        "what": "Marketing at pace",
        "done": "Events, podcast and agency delivering a steady flow of booked leads.",
        "owner": "Marketing / agency",
        "lever": "Lever 10",
        "addedByCfa": false,
        "seat": "marketing"
      },
      {
        "what": "Working-capital discipline holding",
        "done": "Receivables and stock under control; margin at or above the floor.",
        "owner": "Finance + C4A",
        "lever": "Lever 7",
        "addedByCfa": false,
        "seat": "finance"
      },
      {
        "what": "Quarter two OKR review and KPI recalibration",
        "done": "Measures that turned out to drive the wrong behaviour are changed rather than defended.",
        "owner": "HR + C4A",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "hr"
      }
    ]
  },
  {
    "title": "Month 6 - Days 151-180",
    "theme": "Hit the mandate and lock it in",
    "target": "~N46M / mo · 18-20% EBITDA",
    "tasks": [
      {
        "what": "NICU at peak; referral engine self-sustaining",
        "done": "Cots full; referrals flowing without heroics.",
        "owner": "Dr Odedina + BD",
        "lever": "Lever 2",
        "addedByCfa": false,
        "seat": "nicu"
      },
      {
        "what": "Club at first membership milestone",
        "done": "Membership base at its first target; ancillary spend from members flowing.",
        "owner": "Membership lead",
        "lever": "Lever 5",
        "addedByCfa": false,
        "seat": "membership"
      },
      {
        "what": "Plan to hold the run-rate agreed",
        "done": "A costed plan to carry the peak through the low season, signed off by the board.",
        "owner": "Board + C4A",
        "lever": "Lever 8",
        "addedByCfa": false,
        "seat": "board"
      },
      {
        "what": "Re-survey against the baseline",
        "done": "The same instrument the audit used, run again, and the movement shown to staff and board side by side with month 1.",
        "owner": "Culture",
        "lever": "Lever 8",
        "addedByCfa": true,
        "seat": "culture"
      }
    ]
  }
];

export const tasksForSeat = (monthIndex: number, seat: string): PlanTask[] =>
  (PLAN[monthIndex]?.tasks ?? []).filter((t) => t.seat === seat);
